lib: [
  "_build/install/default/lib/maildir/META" {"META"}
  "_build/install/default/lib/maildir/opam" {"opam"}
  "_build/install/default/lib/maildir/maildir.cmi"
  "_build/install/default/lib/maildir/maildir.cmx"
  "_build/install/default/lib/maildir/maildir.cmt"
  "_build/install/default/lib/maildir/maildir.cmti"
  "_build/install/default/lib/maildir/maildir.mli"
  "_build/install/default/lib/maildir/maildir.cma"
  "_build/install/default/lib/maildir/maildir.cmxa"
  "_build/install/default/lib/maildir/maildir.a"
  "_build/install/default/lib/maildir/maildir.cmxs"
]
doc: [
  "_build/install/default/doc/maildir/README.md"
]
